language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: mwbVEdnGxARpwdUJ/dE7nt3fbaD1VOLsCIKDjbt0eC/f6mPsy3nAeV3gtbBDVDCV9MZyCzg91RSU//4AaLpwaGLFMtqPub5WXgvGa202pNa9GVE39tRb9eeNsFugpugg9tvNErvWDxKL11yApwWOeNlnt23Ddv0JUIwRgTpPj4muxQSs3ERmHa5lfe4XJGuDmcG9XVz3zE6Dx0rOO1lbAEy/xwdzPTXom9ogTKKbpIHb/teJMm6tBeMl9pwF97P6bshiPRzSmoGoW3XSpzOpmE4cJZYZQFrgJwuEUUSwx5uT88HmCW9IL83zCo1fr/UeCPoaGz0B6YD50D20Jn9Ltl8+vQiuVRLfScfpBPpDNgsr8FRaY2T6+Do1/o/6x6sXPN7YYyOhZYk3b0XeCNlkn2mIqViJD9nmzBcKtWvbXYERfQXpRbJiz3q0qEeEfP1NJ0zsCb6no77m3fXwUnILoJUv3aFUepAzvDn3FMEgQCAMKjBBWaJGM1VolsHqOFn6kU8PhRHHGesIwhLQLJpNolIwCVXmCik+oso8t75wtaYCUZiej0Enw6nYgi+w9MjdJGLMIDCXXJ5liw+BeNnyuTsEUo9YS8I1JUGVGzAMcj4grsqxPljdcVKfMBi0VDprRWgCYUuHVLKOBS78HXqNAkJBw5c2pGrX8sQdS1sPlr0=
  file:
    - target/cpa-$project_version.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-admin-console-cpa-plugin
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "R2Oblid7CabRBbEafmduGEDsv9iMJxchPgbi4iP8VBfiLunQahkwRJL21xfHNQ77nA5KoE+6aShLLUQ4ZOKoH7OOy0U8mhV3dmGDwdTfop4O7+omeVxWmG9QZQlhNbtg1SoYo/g/K2CDvTwoqV38fE8LIAjMbPmWgmNKDyl+Yb+XavsTN2SG/7eTIHOlEenAMdJyDXMOUmkpVm4jqEqKWvH39Cv2gh/PuAm0jiExPi2yqaRLkRiMB1Mnvg+e0dW9CZqGnraqpEh0X4kyuHmwCNyqrFtg9ytqBVQi8DNMUKV/iatwvqdgZy4SZsqfLmfP+Eb8tfHZ60dtanSsPnzPVQTPcuj6hg4Q9hwmXFYRPVos0s9NvH0jOwbyyaX1neIN/xNp1y8vcJAig/tclIE7mX+21uOKqZS95Ll6rLA+SGGEPBrdSuE3M+7xH7qfSXi1P1w7vj7PmA75wNbFe/aLRQykNxBnY+X+DtVhAf9qsH6jeWpZfP9CvKynEzHLJawdmPWwE55h86Q8w/vdW8HfmG49WB+x7qXawbjc387HTvYyUWkh8NYeepXcZlj8L/dphBAt0YI2KP0RHBtRAnzAnqu0hcoJ2W8Lb3QFg1ubhgH85exjSxrwY2/jtf6NMg3rTCdQYbU51NR0MENpKq+4RTRFncCa2XwXcqeAdGM2hyQ="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-admin-console-cpa-plugin
